#!/usr/bin/env python3
import sys
import yaml
from jinja2 import Template,FileSystemLoader,Environment

yaml_file=sys.argv[1]
method=sys.argv[2]
with open(yaml_file) as f:
    headers,situations=yaml.safe_load_all(f)

env=Environment(loader=FileSystemLoader('templates'),
    line_statement_prefix='%%')
t=env.get_template('method.tex')
sys.stdout.write(t.render(locals()))

